using Microsoft.Extensions.Logging;
using TaskFinisher.Configuration;
using TaskFinisher.Models.Data;
using TaskFinisher.Services.Interfaces;

namespace TaskFinisher.Services;

public sealed class IssueProcessor(
    AppSettings settings,
    IGitHubService gitHub,
    IGitService git,
    IClaudeAgentService claude,
    ILogger<IssueProcessor> logger) : IIssueProcessor
{
    public async Task<DataIssueResult> ProcessAsync(
        DataGitHubIssue issue,
        IProgress<string> progress,
        CancellationToken ct = default)
    {
        var branchName = BuildBranchName(issue);
        string? workDir = null;

        try
        {
            progress.Report("Creating branch on GitHub...");
            await gitHub.CreateBranchAsync(branchName, ct);

            workDir = BuildWorkDir(issue);
            progress.Report("Cloning repository...");
            await git.CloneAsync(gitHub.BuildCloneUrl(), workDir, ct);

            progress.Report($"Checking out branch '{branchName}'...");
            await git.CheckoutBranchAsync(workDir, branchName, ct);

            progress.Report("Starting Claude agent...");
            var prDescription = await claude.RunAgentLoopAsync(issue, workDir, progress, ct);

            progress.Report("Checking for changes...");
            var hasChanges = await git.HasChangesAsync(workDir, ct);
            if (!hasChanges)
                throw new InvalidOperationException("Claude made no changes to the codebase.");

            progress.Report("Committing changes...");
            await git.StageAllAsync(workDir, ct);
            await git.CommitAsync(workDir,
                $"feat: implement #{issue.Number} - {issue.Title}\n\nGenerated by task-finisher using Claude",
                ct);

            progress.Report($"Pushing branch '{branchName}'...");
            await git.PushAsync(workDir, branchName, ct);

            progress.Report("Opening Pull Request...");
            var prUrl = await gitHub.OpenPullRequestAsync(
                branchName,
                $"[AI] #{issue.Number}: {issue.Title}",
                prDescription,
                ct);

            CleanupWorkDir(workDir);
            logger.LogInformation("Issue #{Number} processed successfully. PR: {PrUrl}", issue.Number, prUrl);

            return new DataIssueResult(issue, true, branchName, prUrl, null);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to process issue #{Number}", issue.Number);

            var hint = workDir is not null && Directory.Exists(workDir)
                ? $" Partial work preserved at: {workDir}"
                : string.Empty;

            return new DataIssueResult(issue, false, branchName, null, ex.Message + hint);
        }
    }

    private static string BuildBranchName(DataGitHubIssue issue) =>
        $"task-finisher/issue-{issue.Number}-{Slugify(issue.Title)}";

    private string BuildWorkDir(DataGitHubIssue issue) =>
        Path.Combine(Path.GetTempPath(), "task-finisher", $"{settings.Repo}-{issue.Number}-{Guid.NewGuid():N}");

    private static string Slugify(string title)
    {
        var slug = System.Text.RegularExpressions.Regex
            .Replace(title.ToLowerInvariant(), @"[^a-z0-9]+", "-")
            .Trim('-');
        return slug.Length > 40 ? slug[..40].TrimEnd('-') : slug;
    }

    private static void CleanupWorkDir(string workDir)
    {
        try
        {
            if (Directory.Exists(workDir))
                Directory.Delete(workDir, recursive: true);
        }
        catch
        {
            // Non-critical cleanup failure; ignore
        }
    }
}
