using Spectre.Console;
using TaskFinisher.Configuration;
using TaskFinisher.Models;

namespace TaskFinisher.Services;

public sealed class IssueProcessor
{
    private readonly AppSettings _settings;
    private readonly GitHubService _gitHub;
    private readonly GitService _git;
    private readonly ClaudeAgentService _claude;

    public IssueProcessor(
        AppSettings settings,
        GitHubService gitHub,
        GitService git,
        ClaudeAgentService claude)
    {
        _settings = settings;
        _gitHub = gitHub;
        _git = git;
        _claude = claude;
    }

    public async Task<IssueResult> ProcessAsync(
        GitHubIssue issue,
        IProgress<string> progress,
        CancellationToken ct = default)
    {
        var branchName = BuildBranchName(issue);
        string? workDir = null;

        try
        {
            progress.Report("Creating branch on GitHub...");
            await _gitHub.CreateBranchAsync(branchName, ct);

            workDir = BuildWorkDir(issue);
            progress.Report($"Cloning repository to temp dir...");
            var cloneUrl = _gitHub.BuildCloneUrl();
            await _git.CloneAsync(cloneUrl, workDir, ct);

            progress.Report($"Checking out branch '{branchName}'...");
            await _git.CheckoutBranchAsync(workDir, branchName, ct);

            progress.Report("Starting Claude agent...");
            var prDescription = await _claude.RunAgentLoopAsync(issue, workDir, progress, ct);

            progress.Report("Checking for changes...");
            bool hasChanges = await _git.HasChangesAsync(workDir, ct);
            if (!hasChanges)
                throw new InvalidOperationException("Claude made no changes to the codebase.");

            progress.Report("Committing changes...");
            await _git.StageAllAsync(workDir, ct);
            var commitMsg = $"feat: implement #{issue.Number} - {issue.Title}\n\nGenerated by task-finisher using Claude";
            await _git.CommitAsync(workDir, commitMsg, ct);

            progress.Report($"Pushing branch '{branchName}'...");
            await _git.PushAsync(workDir, branchName, ct);

            progress.Report("Opening Pull Request...");
            var prTitle = $"[AI] #{issue.Number}: {issue.Title}";
            var prUrl = await _gitHub.OpenPullRequestAsync(branchName, prTitle, prDescription, ct);

            CleanupWorkDir(workDir);

            return new IssueResult(issue, true, branchName, prUrl, null);
        }
        catch (Exception ex)
        {
            var hint = workDir is not null && Directory.Exists(workDir)
                ? $" Partial work preserved at: {workDir}"
                : string.Empty;

            return new IssueResult(issue, false, branchName, null, ex.Message + hint);
        }
    }

    private static string BuildBranchName(GitHubIssue issue)
    {
        var slug = Slugify(issue.Title);
        return $"task-finisher/issue-{issue.Number}-{slug}";
    }

    private string BuildWorkDir(GitHubIssue issue) =>
        Path.Combine(
            Path.GetTempPath(),
            "task-finisher",
            $"{_settings.Repo}-{issue.Number}-{Guid.NewGuid():N}");

    private static string Slugify(string title)
    {
        var slug = System.Text.RegularExpressions.Regex
            .Replace(title.ToLowerInvariant(), @"[^a-z0-9]+", "-")
            .Trim('-');
        return slug.Length > 40 ? slug[..40].TrimEnd('-') : slug;
    }

    private static void CleanupWorkDir(string workDir)
    {
        try
        {
            if (Directory.Exists(workDir))
                Directory.Delete(workDir, recursive: true);
        }
        catch
        {
            // Non-critical cleanup failure; ignore
        }
    }
}
